### ISSUE TITLE
error when install 

### ISSUE THREAD

**Issue by srmarjani** [NarimanN2/ParsiAnalyzer#4]
C:\elastic\elasticsearch-6.3.2>bin\elasticsearch-plugin install https://www.dropbox.com/s/2sczcj1372xsq7k/ParsiAnalyzer-%206.3.2.zip?dl=1
-> Downloading https://www.dropbox.com/s/2sczcj1372xsq7k/ParsiAnalyzer- 6.3.2.zip?dl=1
[=================================================] 100%بب
ERROR: This plugin was built with an older plugin structure. Contact the plugin author to remove the intermediate "elasticsearch" directory within the plugin zip.

**Comment by NarimanN2** [comment]
Please tell me what is your elasticsearch version?  
You can use Elasticsearch version 6.3.2 or change plugin version as follows: [incompatible with elasticsearch 6.1](https://github.com/NarimanN2/ParsiAnalyzer/issues/1)

**Comment by srmarjani** [comment]
سلام
من از نسخه 6.3.2 استفاده میکنم.

**Comment by iamajid** [comment]
I use elasticsearch 6.4.0 and have same issue.

**Comment by NarimanN2** [comment]
Hi
the problem is now solved. please download and install the latest version of ParsiAnalyzer.

**Comment by Katerou22** [comment]
ERROR: `elasticsearch` directory is missing in the plugin zip
version: 5.6

Updated:

After fix the elasticsearch directory error by this link:

https://www.dropbox.com/s/0xlrs980er66ati/elasticsearch.zip?dl=1
this error occured! , 

Exception in thread "main" java.lang.IllegalArgumentException: plugin [ParsiAnalyzer] is incompatible with version [5.6.13]; was designed for version [6.4.2]

**Comment by NarimanN2** [comment]
Please download and install Elasticsearch version 6.4.2. you are using an older version of elasticsearch

**Comment by Katerou22** [comment]
what if i want to use this version?

**Comment by NarimanN2** [comment]
1- Download the latest source code
2- Open pom.xml file
3- Under dependecies tag, change elasticserach version from 5.6.3 to 6.1.2 and save it
4- Open plugin-descriptor.properties file
5- Change elasticsearch.version from 6.4.2 to 5.6.13
6- Run this maven command: mvn clean package -DskipTests
7- In the folder target/releases you’ll now find a zip file called ParsiAnalyzer. install the plugin using this command:
bin/elasticsearch-plugin install file:///path/to/ParsiAnalyzer.zip

**Comment by Katerou22** [comment]
`Warning: JAVA_HOME environment variable is not set.
[INFO] Scanning for projects...
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[FATAL] Non-parseable POM ******ParsiAnalyzer-master/pom.xml: processing instruction can not have PITarget with reserveld xml name (position: START_DOCUMENT seen     <?xml ... @1:10)  @ line 1, column 10
 @ 
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project  (******ParsiAnalyzer-master/pom.xml) has 1 error
[ERROR]     Non-parseable POM******ParsiAnalyzer-master/pom.xml: processing instruction can not have PITarget with reserveld xml name (position: START_DOCUMENT seen     <?xml ... @1:10)  @ line 1, column 10 -> [Help 2]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/ModelParseException
`

**Comment by Katerou22** [comment]
[ERROR] No compiler is provided in this environment. Perhaps you are running on a JRE rather than a JDK?
[INFO] 1 error
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.704 s
[INFO] Finished at: 2018-12-19T08:18:50+03:30
[INFO] Final Memory: 13M/303M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.3:compile (default-compile) on project ParsiAnalyzer: Compilation failure
[ERROR] No compiler is provided in this environment. Perhaps you are running on a JRE rather than a JDK?
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
